server:
  port: 20004
  servlet:
    context-path: /skeleton

# 配置文件加密key
jasypt:
  encryptor:
    password: xiaomalover

spring:
  application:
    name: admin-server
  # 数据源
  datasource:
    url: jdbc:mysql://mysql.xm.me:3306/skeleton?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  # Redis
  redis:
    host: redis.xm.me
    #password: skeleton
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000s
    #password: 69F0ef5dd1d62ab48b13834286403A

  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 500000000
      max-request-size: 500000000


# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/**/*Mapper.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xm.admin.*.*.entity
  typeEnumsPackage: com.xm.admin.*.*.entity
  global-config:
    banner: false #mybatis-plus启动图，默认true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  file:
    name: D:/logs/com.xm.admin.log

#文件存储
storage:
  #当前驱动类型，localStorage本地; aliOssStorage阿里云OSS
  type: localStorage
  local:
    rootPath: D:\uploads
    domain: http://img.xm-bt.com/
  alioss:
    accessKeyId: aaaaaaaaaaaaa
    accessKeySecret: bbbbbbbbbbbbbbbbbbbbb
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: test
    fileDir: xboot/demo

auth:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/auth/login"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"
      get:
        - "/captcha/getCaptcha"

jwt:
  config:
    key: xmcoding
    #默认24小时
    ttl: 86400000
    #用户点了记住我，保存7天
    remember: 604800000
